apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-f0qs
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr714-0075-0073-tenant/tkrw-pr714-0075-0073-app/devfile-sample-f0qs@sha256:4fef7164e04cbc8739aa45c1ee1c3e92029f27585d8e36751483d901d8e92cbf
        name: my-nodejs
        resources: {}
status: {}
